### ISSUE TITLE
Podman on Fedora 36: /prometheus.yml: permission denied

### ISSUE THREAD

**Issue by fwiep** [grafana/tutorial-environment#16]
Hello,

Trying to run the tutorial under Fedora 36 with `podman`. Downloading and setup succeed, but one of the containers exits right after launch. It says `permission denied` in the log:
```plain
$ podman logs tutorial-environment_prometheus_1 
ts=2022-10-16T15:47:44.754Z caller=main.go:438 level=error msg="Error loading config (--config.file=/etc/prometheus/prometheus.yml)" file=/etc/prometheus/prometheus.yml err="open /etc/prometheus/prometheus.yml: permission denied"
```
What can I do to make Prometheus start normally, and finally complete the tutorial?

Thanks,
FWieP

**Comment by gargoyle** [comment]
Update the `docker-compose.yml` file and modify the `volumes` line for the `prometheus` service to add `:Z` onto the end. So the full line should be:-

```
services:
  prometheus:
    image: prom/prometheus:v2.34.0
    volumes:
      - ./prometheus/:/etc/prometheus/:Z
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana
```

This is related to Fedora using selinux. More info is on the bind-mount docs:- https://docs.docker.com/storage/bind-mounts/
